import CoreGraphics
import Foundation
import PDFKit

/// A deliberately bounded result for the current Readable PDF exporter.
///
/// PDFKit can read/write PDF documents and expose text, metadata, outlines, and
/// annotations, but PageLumen does not currently author or validate a PDF
/// structure tree. This type therefore reports observable evidence from the
/// generated artifact without claiming PDF/UA conformance.
public struct PDFUADirectionReport: Codable, Equatable, Sendable {
    public enum CheckStatus: String, Codable, Equatable, Sendable {
        case passed
        case unavailable
        case notImplemented
    }

    public struct Check: Codable, Equatable, Sendable, Identifiable {
        public let id: String
        public let status: CheckStatus
        public let detail: String

        public init(id: String, status: CheckStatus, detail: String) {
            self.id = id
            self.status = status
            self.detail = detail
        }
    }

    public let generatedPageCount: Int
    public let checks: [Check]
    public let isPDFUAConformant: Bool
    public let recommendedAlternative: String

    public init(
        generatedPageCount: Int,
        checks: [Check],
        isPDFUAConformant: Bool = false,
        recommendedAlternative: String = "Tagged HTML"
    ) {
        self.generatedPageCount = generatedPageCount
        self.checks = checks
        self.isPDFUAConformant = isPDFUAConformant
        self.recommendedAlternative = recommendedAlternative
    }

    public var report: String {
        var lines = [
            "Readable PDF accessibility direction",
            "Pages: \(generatedPageCount)",
            "PDF/UA conformance: not asserted"
        ]
        for check in checks {
            lines.append("- [\(check.status.rawValue)] \(check.id): \(check.detail)")
        }
        lines.append("Recommended accessibility export: \(recommendedAlternative)")
        return lines.joined(separator: "\n")
    }
}

/// Produces deterministic evidence for the current PDF prototype.
///
/// The checks intentionally separate what can be observed in the generated
/// PDF from structure requirements that are not authorable/inspectable through
/// the supported PageLumen API surface. A future specialist PDF library or
/// approved external validator can replace this boundary without changing the
/// export label or silently upgrading the conformance claim.
public enum PDFUADirectionValidator {
    public static func assess(pdfData: Data) -> PDFUADirectionReport {
        guard let pdf = PDFDocument(data: pdfData) else {
            return PDFUADirectionReport(
                generatedPageCount: 0,
                checks: [
                    .init(id: "pdf.parseable", status: .unavailable, detail: "The generated bytes are not a readable PDF document.")
                ]
            )
        }

        let hasText = !(pdf.string?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
        let attributes = pdf.documentAttributes ?? [:]
        let hasTitle = (attributes[PDFDocumentAttribute.titleAttribute] as? String)?.isEmpty == false

        return PDFUADirectionReport(
            generatedPageCount: pdf.pageCount,
            checks: [
                .init(
                    id: "pdf.parseable",
                    status: .passed,
                    detail: "PDFKit opened the generated artifact."
                ),
                .init(
                    id: "pdf.selectable-text",
                    status: hasText ? .passed : .unavailable,
                    detail: hasText ? "The artifact exposes selectable text through PDFKit." : "No selectable text was exposed by PDFKit."
                ),
                .init(
                    id: "pdf.title-metadata",
                    status: hasTitle ? .passed : .unavailable,
                    detail: hasTitle ? "A document title is present in PDF metadata." : "The artifact has no readable title metadata."
                ),
                .init(
                    id: "pdf.language",
                    status: .notImplemented,
                    detail: "A document language is not authored or validated by the current CGContext/PDFKit export path."
                ),
                .init(
                    id: "pdf.marked-content",
                    status: .notImplemented,
                    detail: "Marked-content authoring is not implemented in the current exporter."
                ),
                .init(
                    id: "pdf.structure-tree",
                    status: .notImplemented,
                    detail: "A PDF structure tree for headings, tables, and reading order is not authored or validated."
                ),
                .init(
                    id: "pdf.figure-alternate-text",
                    status: .notImplemented,
                    detail: "Figure alternate text is preserved by Tagged HTML, not represented in this PDF prototype."
                ),
                .init(
                    id: "pdf.table-semantics",
                    status: .notImplemented,
                    detail: "Table header/scope semantics are not represented in this PDF prototype."
                )
            ]
        )
    }
}
